project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - download.qmd

website:
  title: "Kruhy"
  search: true
  navbar:
    left:
      - href: download.qmd
        text: Na stiahnutie
      - href: about.qmd
        text: O projekte

lang: sk

format:
  html:
    css: styles.scss
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: Obsah
    smooth-scroll: true
    page-layout: article
    theme: cosmo

execute:
  freeze: auto
