[]{#word-principy-kruhov}

# Aké sú princípy Kruhov?

## Princípy Kruhov sú iba odporúčania?

- Kruhy sú definované nasledovnými odporúčaniami, ktoré sú iba dobroprajným odporúčaním autorov myšlienky Kruhov.
- Tieto odporúčané princípy si preto členovia jednotlivých kruhov samozrejme môžu následne meniť, dopĺňať a vylepšovať, ako sami uznajú za vhodné.
- Kruhy sú riadené členmi kruhov tak, že o všetkom v kruhu rozhodujú členovia daného kruhu.
- Nie sú definované žiadne funkčné obdobia žiadneho funkcionára, žiaden konkrétny spôsob jeho voľby, ani odvolania, žiadna povinná štruktúra, ani žiadne povinnosti členov kruhov.
- O všetkom rozhodujú členovia kruhu sami a prirodzene tiež sami znášajú dôsledky svojich rozhodnutí pred členmi iných kruhov. Preto je v záujme každého člena a každého kruhu, aby kruh v ktorom je členom fungoval čo najlepšie a teda podľa čo možno najlepších princípov.

## Aké sú odporúčané základné princípy Kruhov?

1. Organizácia Kruhy (OK) je organizovaná v jednotlivých kruhoch, ktorých počet je neobmedzený.
    - *Pozn. jednotlivé kruhy píšeme s malým k, celú Organizáciu Kruhy s veľkým K, skrátene OK.*
1. Členom kruhu je ten, kto sa prihlási do niektorého kruhu a členovia kruhu ho prijmú.
1. Členovia kruhu môžu rozhodnúť o prijatí aj vylúčení člena zo svojho kruhu.
1. Jeden človek môže byť členom viacerých kruhov, ak ho tieto prijmú.
1. Každý kruh by mal mať svojho (aspoň jedného) zástupcu.
    - [Prečo sú potrební zástupcovia kruhov?](#word-preco-su-potrebni)
1. Počet členov v jednotlivých kruhoch odporúčame udržiavať v určitom rozumnom rozmedzí.
    - [Aký je rozumný počet členov kruhu?](#word-optimalny-pocet-clenov)
1. Čím viac kruhov a členov OK, tým lepšie.
    - Prečo? Pretože každý človek môže byť prínosom, svojou pomocou, nápadom atď...

::: {.word-note}
*Poznámka: Najlepšie by bolo, ak by v OK bolo čo najviac ľudí, akokoľvek prínosných pre OK.*
:::
