[]{#word-statostrana-kruhy}

# Prečo Celoslovenské Kruhy?

Uvažujme teraz o Kruhoch maximalisticky (v rámci SR) t.j. ako o celo-štáto-hnutí, alebo politickej strane, ktorá organicky integruje väčšinu slovenských občanov schopných a ochotných participovať na riadení spoločnosti pre spoločné dobro celej spoločnosti, v jednom organickom celku, v jednej organizácii, ktorej ambíciou je stať sa ak nie jedinou, tak najvýznamnejšou politickou silou na Slovensku.

Toto by malo byť jedným z cieľov členov OK, pretože by to riešilo krízy súčasného politického systému/režimu ako aj celej spoločnosti, ktoré sú spôsobené necnosťami väčšiny účastníkov politickej scény (zhora mocensky ako armády riadených  (ZMAR) politických strán), t.j. ich rozhádanosťou, roznenávidenosťou, rozdrobenosťou, pokrytectvom/pretvárkou,  malomyseľnosťou, prerasteným egoizmom, ignorantstvom, nenažranosťou, atď. atď. atď...

Napriek tomu, že súčasná organizačná štruktúra štátnych orgánov a celej verejnej správy má ďaleko k optimálnej, ak ju chcú členovia OK zlepšiť, tak najefektívnejšie ako môžu vplývať na jej zmenu, je čo najviac svoju vlastnú štruktúru Kruhov prispôsobiť aktuálnej štruktúre štátnych a verejných orgánov. Vytvoriť de fakto paralelné štruktúry štátnych a verejných orgánov a orgánov samosprávy, v rámci OK a podľa princípov OK.

Štruktúra OK, ktorá napodobní štruktúru verejných inštitúcií, umožní členom Kruhov lepšie porozumieť činnostiam týchto štátnych a verejných inštitúcií, ich štrukturálnym nedostatkom a ukážu sa im aj možnosti ich nápravy.

::: {.word-note}
*Upozornenie 1: existujúca organizačná štruktúra štátnych orgánov definovaná Ústavou SR je podľa názoru autorov tohoto dokumentu nevyhovujúca a zdeformovaná ZMAR organizáciami (a ich predstaviteľmi a členmi), a to na všetkých úrovniach štátu a spoločnosti. Aj na miestnej úrovni, v samospráve miest a obcí, aj na úrovni VÚC a aj na celoštátnej úrovni, pretože bola vytvorená a prispôsobená práve týmto deformovaným a deformujúcim aktérom politickej scény (zhora mocensky riadeným dole t.j. perverzne/opačne/neprirodzene).*
:::

::: {.word-note}
*Poznámka: všetko v prírode prirodzene rastie zdola hore. Iba ZMAR organizácie, egopatmi vytvorené, „rastú“ opačne zhora dole, t.j. smerujú ľudí a celú spoločnosť dole. A to sa týka väčšiny súčasných organizačných štruktúr, politických strán, korporácií, masmédií, cirkví, armád atď.*
:::

::: {.word-note}
*Práve pre túto perverziu, neprirodzenú zvrátenosť z hora dole, je aj súčasná štruktúra orgánov SR (o.i.), t.j. NRSR, vláda, ústavný súd, prokuratúra, samosprávy atď. a všetky ich kompetencie a pôsobenie v spoločnosti neraz v protiklade k potrebám väčšiny občanov, obcí, miest a regiónov Slovenska.*
:::

::: {.word-note}
*Koncentrácia moci a výhod vrcholových členov týchto orgánov a mocenských organizácií je neraz tiež perverzná. V parlamente/NRSR by napr. nemali byť vyhradené miesta len pre straníkov ZMAR politických strán, plných egopatov a ich podržtašiek tak, ako je tomu v súčasnosti. Miesto nich by tam mali byť najlepší zástupcovia jednotlivých regiónov (okresov/kantónov), ktorí by boli priamo vybraní, kontrolovaní a prípadne priebežne vymieňaní za ešte lepších, ak sa takí nájdu, obyvateľmi daného regiónu (okresu, alebo kantónu).*
:::

::: {.word-note}
*Detto vláda by mala pozostávať z odborníkov (bez ohľadu na ich ideologickú, alebo politickú príslušnosť, alebo nepríslušnosť), vybraných parlamentom (zástupcami jednotlivých regiónov) na základe riadneho výberového konania a preukázanej najväčšej odbornosti s pripraveným projektom plánu činností daného ministerstva (na dané volebné obdobie a optimálne aj so strategickým výhľadom na nasledujúce obdobia). Nie tak, ako je tomu dnes, že sa ministri vyberajú na základe politickej príslušnosti a šírky lakťov jednotlivých egopatov snažiacich sa zmocniť sa stoličky ministra a rozpočtu ministerstva neraz bez akýchkoľvek predpokladov vykonávať takto zodpovednú funkciu.*
:::

::: {.word-note}
*Aj na úrovni VÚC je prílišná koncentrácia moci spôsobená okrem iného aj veľkosťou jednotlivých VÚC. Tie sú tak občanom zbytočne príliš vzdialené. Pre občanov SR bližšie a pre jednotlivé regióny oveľa prospešnejšie by bolo, ak by druhou úrovňou samosprávy (verejnej správy) boli prirodzené historické/kultúrne regióny (resp. okresy/kantóny) namiesto súčasných umelo vytvorených VÚC/žúp.*
:::

::: {.word-note}
*Samosprávy miest a obcí v SR zas trpia opačným extrémom. Príliš veľká rozdrobenosť samospráv je zdrojom ich veľkej neefektivity. Východiskom by bolo spojiť zdroje a organizáciu malých obcí do väčších miestnych celkov - kooperujúcich municipalít. Ušetrilo by sa tým v SR tisíce nadbytočných funkcionárov a funkcií, ktoré dnes musia byť v každej z tých tisícov obcí obsadené (pričom stovky obcí majú menej ako 200 obyvateľov...).*
:::

::: {.word-note}
*To, že občania nemajú prakticky žiadnu možnosť čokoľvek meniť priamo, pretože podmienky pre konanie referenda sú pre občanov na všetkých úrovniach ťažko dosiahnuteľné a neraz nemožné, je možno aj zbytočné písať. V ZMAR politickom režime sú potreby a názory miliónov občanov na poslednom mieste, aby potreby a názory zopár egopatov mohli byť na prvom.*
:::

::: {.word-note}
*Všetky tieto problémy však majú jednu spoločnú príčinu, pomenovanú vyššie. T.j. to, že spoločnosť je zhora mocensky ako armáda riadená dole ZMAR štruktúrami, ktoré všetky tieto problémy vytvorili a neustále zhoršujú. *

*To ale na druhej strane znamená, že všetky spomínané problémy majú aj jedno spoločné riešenie, opísané v tomto dokumente, t.j. riadenie spoločnosti nie zhora mocensky dole, ale naopak. Napr. pomocou Kruhov.*
:::

::: {.word-note}
*Ako na to?*
:::

## Ako by mohla vyzerať štruktúra Celoslovenských Kruhov?

Najefektívnejšie pôsobenie na verejnú správu dosiahnu členovia Kruhov tak, že prispôsobia štruktúru svojich Kruhov orgánom verejnej správy. Nižšie uvedieme niekoľko možností, ako to môžu členovia OK spraviť:

[]{#word-na-uro}

### ... na úrovni miestnej samosprávy?

V závislosti od počtu členov OK v konkrétnom v meste/obci:

Ak je počet členov OK v obci/meste ešte relatívne malý a dostatočný iba vytvorenie jedného kruhu, aj tak sa môžu členovia tohto jedného kruhu samozrejme venovať o.i. aj samospráve. T.j. napr. môžu sledovať činnosť miestnych poslancov a starostu/primátora. Keď prídu voľby budú s ich aktivitami lepšie zoznámení a môžu vo voľbách podporiť tých s aktivitami ktorých boli spokojní. Ak s aktivitami nejakých poslancov/starostu/primátora nie sú spokojní, tak prípadne navrhnúť miesto nich vhodnejších kandidátov, ktorých by v predvolebnej kampani a vo voľbách podporovali.

Čím je počet členov Kruhov v obci/meste vyšší, tým je to jednoduchšie. Ak je napr. členov OK viac, takže môžu vytvoriť viacero samostatných kruhov, napr. toľko, koľko je v obci/meste volebných obvodov, tak to majú členovia každého z týchto kruhov jednoduchšie v tom, že nemusia sledovať činnosť všetkých poslancov, ale môžu sa miesto toho sústrediť len na poslancov zo svojho volebného obvodu. Môžu ich preto intenzívnejšie sledovať, byť s nimi v kontakte, komunikovať a spolupracovať s nimi pri svojich aktivitách. V prípadne, že s ich činnosťou sú spokojní, môžu ich pri voľbách podporovať. V opačnom prípade môžu miesto nich vybrať nejakých vhodnejších kandidátov a v predvolebnej kampani a vo voľbách podporovať týchto.

Na lepšiu komunikáciu a koordináciu medzi týmito viacerými kruhmi v danom meste/obci je pre členov kruhov účelné vytvoriť aj kruh ich zástupcov (t.j. kruh 2. stupňa) tak, aby sa spoločne všetky tieto kruhy mohli navzájom rýchlejšie a lepšie koordinovať pri svojich aktivitách. Napr. aj pri výbere vhodných kandidátov na poslancov, alebo na starostu/primátora obce/mesta.

Ešte jednoduchšie pre členov OK je to pri ešte vyššom počte členov Kruhov v meste/obci, ktorý by im umožnil napr. vytvoriť toľko kruhov, koľko je v obci poslancov. Takto by v každom kruhu mohli členovia sústrediť svoju pozornosť iba na jedného poslanca. Sledovať jeho aktivity a vo voľbách ho buď podporiť, alebo hľadať miesto neho vhodnejšieho kandidáta, ktorého by chceli vo voľbách do zastupiteľstva podporiť miesto neho.

Samozrejme pre všetkých členov všetkých kruhov v danej obci, alebo meste je účelné sledovať aj aktivity starostu, alebo primátora a pred voľbami sa zariadiť podľa toho, či sú s jeho aktivitami spokojní. Ak nie sú, tak miesto neho hľadať lepšieho kandidáta, ktorého by vo voľbách na starostu/primátora mohli nominovať a podporiť.

Najjednoduchšie je to samozrejme pri čo najväčšom počte členov Kruhov v meste/obci. Takto sa môžu členovia v kruhoch zorganizovať tak, že ich kruhy sú najbližšie mieste ich bydliska. Zástupcovia týchto kruhov (1. stupňa) môžu zastupovať členov OK napr. z jednej ulice, alebo susediacich ulíc, bytového domu, alebo sídliska, alebo nejakej inej súvislej časti obce/mesta. Potom môže aktivity jedného poslanca sledovať a kontrolovať dokonca viacero kruhov a ich zástupcov (v kruhu 2. stupňa). Môžu byť s daným poslancom v úzkom kontakte a ak sú s jeho aktivitami členovia týchto všetkých kruhov spokojní, tak ho môžu vo voľbách podporovať. Ak nie tak môžu vybrať a navrhnúť iného kandidáta za poslanca. Zástupcovia kruhov 2. stupňa môžu vytvoriť aj kruh 3. stupňa na zabezpečenie lepšej komunikácie a koordinácie všetkých týchto kruhov. Spoločne môžu potom všetci členovia hľadať a vo voľbách podporovať podľa nich najvhodnejšieho kandidáta na starostu a primátora, pričom podpora všetkých týchto kruhov a ich členov v kampani dáva vybraným kandidátom najväčšiu šancu vo voľbách.

::: {.word-note}
*Poznámka 1: V prípade väčších obcí a miest s väčším počtom poslancov, ako je [rozumný počet členov kruhu](#word-optimalny-pocet-clenov), môže byť účelné vytvoriť aj viac ako jeden kruh na najvyššom stupni v obci/meste. Vybraní kandidáti týchto kruhov potom môžu byť kandidátmi Kruhov na starostu/primátora a aj jeho zástupcu/zástupcov. Takto môže mať každý kruh na najvyššom stupni v meste/obci svojho kandidáta buď na starostu/primátora, alebo na jeho zástupcu.*
:::

::: {.word-note}
*Poznámka 2: V každom prípade až v samotných voľbách sa rozhodne, ktorí kandidáti (a či vôbec) budú zvolení za poslancov, starostu/primátora.*
:::

::: {.word-note}
*Poznámka 3: Kandidáti Kruhov na starostu/primátora a jeho zástupcov môžu medzi sebou uzavrieť dohodu, že vo voľbách nebudú kandidovať všetci na funkciu starostu/primátora a miesto toho všetci podporia jedného spoločného kandidáta Kruhov na funkciu starostu/primátora, aby ich spoločný kandidát mal väčšiu šancu vo voľbách a nerozdeľovali sa vo voľbách hlasy medzi viacerých kandidátov Kruhov. Súčasťou tejto dohody môže byť napr. to, že ak vo voľbách daný kandidát Kruhov na starostu/primátora zvíťazí, tak automaticky menuje za svojich zástupcov ostatnými kruhmi navrhovaných kandidátov na zástupcov starostu/primátora.*
:::

Takýmto spôsobom sa môžu efektívne prepojiť občania v kruhoch s miestnou samosprávou, keďže cielene prispôsobili štruktúru svojich kruhov existujúcej štruktúre verejnej správy na úrovni samosprávy. Členovia kruhov takto majú najpriamejší kontakt so svojimi kandidátmi pred voľbami a po voľbách so svojimi zástupcami v samospráve.

Ak členovia Kruhov nominujú na funkcie v miestnej samospráve členov OK (spomedzi seba), následne po voľbách budú môcť riešiť všetky otázky v kompetencii miestnej samosprávy so svojimi zvolenými zástupcami na pravidelnej a otvorenej báze priamo na svojich pravidelných stretnutiach vo svojich kruhoch, nie niekde na úrade alebo pri zasadnutiam miestneho, alebo mestského zastupiteľstva.

::: {.word-note}
*Poznámka 4: V ďalšom texte sú uvedené príklady, ako je možné kruhy organizovať na vyšších úrovniach samosprávy resp. verejnej správy spoločnosti. Analogicky kruhy fungujú aj na vyšších úrovniach verejnej správy takže dochádza k neprerušenej kontinuite delegovania moci a spätnej väzby od občana až po najvyššie miesta verejnej správy.*
:::

::: {.word-note}
*Z dôvodov uvedených v Upozornení 1. (t.j. v súčasnosti nevyhovujúcej organizačnej štruktúre verejnej správy) je to však čím ďalej tým komplikovanejšie, viac ako by mohlo, resp. malo byť. Preto aj nasledujúci popis nie je tak jednoduchý na čítanie a pochopenie, ako by mohol a mal byť. Pre pochopenie princípov fungovania Kruhov však nie je ani potrebné ho čítať a presne chápať. Stačí chápať vyššie uvedené [Princípy Kruhov](#word-principy-kruhov).*
:::

::: {.word-note}
*Tak či onak je to iba jedna z mnohých možností ako sa členovia môžu zorganizovať v OK. Možností ako najlepšie mapovať štátne inštitúcie v Kruhoch je mnoho a to v každej obci, okrese a kraji, nehovoriac o celom štáte. Štruktúra Kruhov sa tak či onak bude stále meniť a vyvíjať v závislosti na počte členov Kruhov, ich preferenciách, potrebách a prípadne aj meniacej sa štruktúre štátnych a verejných orgánov atď.*
:::

::: {.word-note}
*V každom prípade to budú členovia Kruhov, ktorí budú rozhodovať o štruktúre svojich kruhov v ktorých sú členmi a to zrejme podľa toho aké úlohy a ciele si pre seba určia a ako sa medzi sebou dohodnú. Tiež to bude zrejme závisieť od štruktúry štátnych orgánov, ktoré sa tiež môžu časom meniť, a ktoré, ako dúfame sa aj časom budú meniť a zlepšovať v prospech všetkých občanov za aktívneho prispenia práve členov OK.*
:::

### ... na vyšších úrovniach?

Zástupcovia kruhov najvyšších mestských a obecných stupňov v danom okrese (t.j. možno aj kandidáti OK na starostov obcí a primátorov miest?), vytvoria v okrese kruh najvyššieho okresného stupňa (predpokladajme, že 4-tého stupňa - v závislosti od počtu členov OK v danom okrese.). Tento kruh zástupcov OK bude zastupovať všetky kruhy a všetkých členov OK v danom okrese a mal by preto navrhovať kandidáta OK za poslanca do NRSR za daný okres (región/kantón).

V SR je aktuálne 79 okresov a 150 poslancov v NRSR. Väčšie okresy preto môžu nominovať aj na viac kandidátov za poslancov do parlamentu/NRSR (v závislosti od počtu obyvateľov daného okresu). V tých okresoch, na ktoré by pripadlo viacero poslancov by preto bolo asi najlepšie, aby zástupcovia kruhov na najvyššom stupni v okrese (t.j. napr. 4-tom) zorganizovali tak, aby vytvorili nie jeden kruh, ale toľko kruhov, koľko poslancov do NRSR prislúcha pre daný okres. Tak, aby každý takto vytvorený kruh si mohol zvoliť svojho kandidáta na poslanca vo voľbách do NRSR. Tak, aby po úspešných voľbách členovia tohto kruhu (pravdepodobne kandidáti na starostov a primátorov OK z daného okresu) mohli na svojich pravidelných stretnutiach v kruhu spolupracovať so svojim zvoleným poslancom parlamentu/NRSR.

Tieto najvyššie kruhy na úrovni okresov, reprezentujúce okresy, zároveň navrhujú a vyberajú aj kandidátov za poslancov do VÚC a to tak, aby ich počet korešpondoval s počtom kandidátov, ktorí môžu byť za daný okres vo voľbách zvolení. Poslancov vo VÚC zo všetkých okresoch každej VÚC je v súčasnosti od 40 do 65. Vzhľadom k tomuto vysokému počtu potrebných kandidátov na funkciu poslancov VÚC, je asi najlepšie, aby sa títo zvolení kandidáti OK na poslancov VÚC zorganizovali nie v jednom veľkom a neefektívnom 60-65 člennom kruhu (viď. [rozumný počet členov kruhu](#word-optimalny-pocet-clenov)), ale vo viacero kruhov (už na 5. stupni) v každom VÚC. A to tak, aby kandidáti z jedného, prípadne viacerých susediacich okresoch, vytvorili kruhy s[ rozumným počtom členov](#word-optimalny-pocet-clenov). Zvolení zástupcovia týchto (predpokladajme 3-5-tich) kruhov (5. stupňa) potom budú kandidátmi Kruhov na posty predsedu a podpredsedov VÚC.

Po úspešných voľbách tak budú môcť zvolení kandidáti Kruhov, t.j. predseda VÚC a poslanci VÚC v zastupiteľstve VÚC potvrdiť aj ostatných zvolených zástupcov Kruhov za podpredsedov VÚC. Takto budú zvolení poslanci VÚC môcť priamo v každom z ich takto vytvorených kruhoch (5. stupňa) spolupracovať buď s predsedom VÚC, alebo podpredsedom VÚC vo svojom kruhu.

Takýmto spôsobom budú môcť mať všetci členovia OK prístup ku všetkým voleným verejným zástupcom od poslancov miestnej samosprávy, cez starostov miest a obcí a ich zástupcov, poslancov VÚC, po predsedov VÚC a ich zástupcov, až po poslancov NRSR asi najpriamejším a najprirodzenejším spôsobom aký je možný dosiahnuť v súčasnom systéme/režime. Takto sa všetci členovia OK budú môcť efektívnejšie spolupodieľať na lepšom fungovaní správy vecí verejných v prospech všetkých občanov.

### ... na celoštátnej úrovni?

#### ... v parlamente/NRSR?

Ako už bolo uvedené kandidáti na poslancov parlamentu/NRSR sa môžu navrhovať už na okresnej úrovni a to preto, že je to najnižšia úroveň na ktorej je možné navrhovať kandidátov na poslancov NRSR. Pretože aktuálne je 79 okresov a poslancov až 150. T.j. v súčasnom systéme by mali niektoré okresy mať nárok aj viac ako jedného poslanca (podľa veľkosti okresu).

Pre občanov SR je dobré navrhovať kandidátov na poslancov NRSR na čo najnižšej úrovni, pretože čím sú navrhovaní na nižšej úrovni tým sú bližšie k občanom a ich kontrole. Preto je najvýhodnejšie pre členov OK vytvoriť na okresnej úrovni OK práve toľko kruhov na najvyššom okresnom stupni, koľko je kandidátov/poslancov v NRSR (t.j. 150). Takto môže aktivity každého poslanca NRSR sledovať celá sieť okresných kruhov od prvého do štvrtého stupňa, ktorí si ho navrhli a zvolili za svojho zástupcu v NRSR.

Kandidát OK na poslanca, ktorý nebude vo voľbách zvolený za poslanca, sa prípadne môže stať asistentom niektorého zo zvolených poslancov, ak s tým tento súhlasí. Napr. ak nejaký okres má na kandidátnej listine OK možnosť delegovať dvoch poslancov (t.j. na najvyššom stupni v okrese sú teda dva kruhy a každý z nich nominuje na kandidátku OK jedného kandidáta na poslanca do parlamentu/NRSR), ale vo voľbách do NRSR je zvolený iba jeden z nich, tak najspravodlivejšie by asi bolo, ak by si ten zvolený poslanec toho druhého nominovaného kandidáta OK z okresu vybral za svojho asistenta.

Takto by mohol byť po voľbách členom najvyššieho počtu okresných kruhov buď poslanec, alebo asistent poslanca, s ktorým by mohli ostatní členovia OK z daného okresu spolupracovať priamo na pravidelných stretnutiach prostrednítvom svojich kruhov.

#### ... vo vláde?

Členovia OK môžu ešte pred voľbami do NRSR vytvoriť tieňovú vládu, ktorá by tvorila odborný program jednotlivých ministerstiev. A v ktorej by sa profilovali odborníci v jednotlivých odboroch tak, aby členovia OK boli pripravení aj na prípadné víťazstvo vo voľbách a prevzatie výkonnej moci, t.j. vlády.

Za týmto účelom by mohli členovia OK vytvoriť, toľko kruhov, koľko je práve ministerstiev (+-). O členstvo v týchto “odborných kruhov jednotlivých ministerstiev“ (ďalej skrátene nazývaných “odborné kruhy“) by sa mali uchádzať v prvom rade kandidáti OK na poslancov NRSR (ktorých počet by mal byť v súčasnosti až 150). Títo by sa mali hlásiť do týchto odborných kruhov podľa svojich vlastných odborností/preferencií tak, aby každý poslanec bol členom aspoň jedného takéhoto odborného kruhu. A to preto, aby každý z nich mohol byť oboznámený s aspoň jednou oblasťou/odbornosťou (ním vybraného ministerstva), ktorého odborného kruhu je členom. Aby danej oblasti dobre rozumel a mohol tak hodnotiť materiály daného ministerstva aj po vecnej aj odbornej stránke ako aj odbornosť samotného ministra. Prípadne bol schopný formulovať aj svoje odborné výhrady, alebo podať a predniesť aj odborne odôvodnený návrh na odvolanie ministra v NRSR v prípade jeho nejakého pochybenia, alebo zlyhania.

Spolu s týmito kandidátmi OK na poslancov by mali v týchto odborných kruhoch spolupracovať aj všetci odborníci (či už členovia, alebo nečlenovia OK, alebo prizvaní odborníci), ktorí majú záujem o prácu na príprave programu daného ministerstva, prípadne jeho následnej realizácie. Títo všetci odborníci by sa mali hlásiť za členov týchto jednotlivých odborných kruhov spolu s kandidátmi OK na poslancov NRSR. Potom, čo títo odborníci preukážu svoju odbornosť, by ich tieto kruhy mali prijať a začleniť do práce na odbornom programe.

V prípade, ak by počet členov niektorého z týchto odborných kruhov prekročil [optimálny počet členov kruhov](#word-optimalny-pocet-clenov), tak sa členovia tohto kruhu môžu v prípade potreby rozhodnúť daný odborný kruh rozdeliť na viacero odborných kruhov 1. stupňa a kruh zástupcov týchto odborných kruhov (odborný kruh 2. stupňa). Podobne ako na Obr.1. Každý z týchto odborných kruhov 1. stupňa si potom môže zobrať za úlohu vypracovať časť agendy, resp. programu daného ministerstva, aby si čo najefektívnejšie rozdelili prácu.

V tomto prípade je vhodné, aby členom každého odborného kruhu 1. stupňa bol aspoň jeden kandidát OK na poslanca NRSR tak, aby každú časť agendy/programu každého ministerstva ovládal a mohol kontrolovať aspoň jeden kandidát OK na poslanca NRSR (v prípade zvolenia po voľbách poslanec, alebo asistent poslanca). Aby tak v NRSR vždy bol aspoň jeden poslanec OK (prípadne asistent poslanca), ktorý dostatočne dobre, až výborne rozumie každému z predkladaných návrhov zo strany každého ministerstva.

Takýmto spôsobom všetci poslanci OK v NRSR by mali vždy možnosť každú predkladanú vec konzultovať priamo s nejakým svojim kolegom z OK, poslancom NRSR (alebo jeho asistentom), ktorý je v danej téme ak nie naslovovzatým odborníkom, tak veľmi dobre zorientovaný a pozná v danej oblasti dosť odborníkov na ktorých sa môže obrátiť, prípadne na ktorých môže iných poslancov odkázať. S týmito odborníkmi potom môžu každú vec konzultovať, prípadne si ich môžu aj zavolať do NRSR, aby im tam spravili odbornú oponentúru predkladaných návrhov a pod.

Odborné kruhy pred voľbami do NRSR vytvárajú volebný program OK. Členovia v nich medzi sebou komunikujú, lepšie sa pri spolupráci na spoločnom programe spoznávajú a organizujú sa v štruktúre týchto odborných kruhov na viacerých stupňoch. Po prípadných úspešných voľbách (alebo po odvolaní predchádzajúceho ministra parlamentom/NRSR) tak v prípade potreby môžu spomedzi seba navrhnúť a nominovať kandidátov OK na štátne funkcie na daných ministerstvách. T.j. kandidátov OK na ministrov, štátnych tajomníkov a pod. Navrhovaní kandidáti OK na ministrov sa uchádzajú o podporu väčšiny poslancov/členov parlamentu/NRSR s pripraveným návrhom programu OK na funkciu ministra.

Poslancami v parlamente/NRSR zvolení kandidáti OK na ministrov sa následne po akceptácii ich kandidatúry prezidentom SR, stávajú ministrami, t.j. súčasťou vlády SR.

[]{#word-prezident}

#### Prezident?

Zástupcovia najvyšších stupňov jednotlivých odborných kruhov OK, zastupujúci jednotlivé odbornosti OK (ministerstvá) spoločne tvoria najvyšší kruh členov OK v SR - kruh najvyššieho odborného stupňa. Tento kruh preto zastupuje všetkých členov OK a všetky odbornosti OK a v spolupráci s ostatnými kruhmi a členmi OK navrhuje možných kandidátov OK na funkciu prezidenta.

Nominácii konkrétneho jedného kandidáta OK na funkciu prezidenta by mali predchádzať primárne viackolové voľby medzi všetkými prihlásenými, alebo vytipovanými kandidátmi OK na funkciu prezidenta, a to vo všetkých kruhoch OK a medzi všetkými členmi OK, pretože prezidenta v SR tiež volia všetci občania. Preto aj primárne prezidentské voľby kandidáta OK na prezidenta by sa mali čo najviac priblížiť aktuálnej praxi, spôsobe a nastavení štátnych orgánov a ich procedúr.

::: {.word-note}
*Poznámka pod čiarou (mimo súčasný politický systém/režim): To, že milióny ľudí je obťažovaných voľbou jedného konkrétneho funkcionára do jednej konkrétnej funkcie a to dokonca na viac krát (viac-kolovo) vo všeobecných voľbách (všetkých občanov), nie je veľmi praktické ani nákladovo efektívne (napísané veľmi kulantne). Napísané priamo, jedná sa (v SR) asi o najextrémnejší prípad papalášizmu, resp. egopatizmu, aký ZMAR organizácie po r. 89 dokázali v SR vyprodukovať. Ale je to dobrá ukážka ich zvrátenosti/perverzie.*
:::

::: {.word-note}
*Navyše sa jedná o funkciu, ktorá je v SR tradične skôr formálna (t.j. +- na okrasu. A niekedy dokonca až potenciálne škodlivá, takže sa v minulosti neraz stávalo, že by bolo lepšie, keď by papaláš na tejto funkcii robil menej, alebo nič). Pre porovnanie v nepomerne bohatšom Švajčiarsku napr. formálnou funkciou prezidenta poverujú každý rok členovia parlamentu jedného z členov vlády. A je to preňho len vedľajší úväzok popri svojej bežnej ministerskej práce. A samozrejme nepotrebuje k tomu ani hrad ani palác, ani prezidentskú kanceláriu s mnohamiliónovým rozpočtom s mnohými pomocníkmi, služobníctvom, podržtaškami, dvereotváračmi atď. atď. atď.*
:::

::: {.word-note}
*Zmeniť tento konkrétny papalášizmus v SR (napr. podľa švajčiarskeho príkladu) sa však dá iba zmenou Ústavy. Nateraz nám môže funkcia prezidenta SR a jeho super-neefektívny spôsob voľby (a odvolania), jeho všetky možné benefity, platy, náhrady, rozpočty a náklady jeho kancelárie, hrady a zámky, doživotné renty a iné peňažné a nepeňažné výhody... a na druhej strane prakticky žiadne povinnosti, ani zodpovednosti za čokoľvek čo ráči vykonať, alebo neráči vykonať, poslúžiť ako ukážkový, študijný príklad toho, čo vrcholní protagonisti tohto režimu (poväčšine egopati, deprivanti, sociopati a psychopati) považujú za ideál a k čomu nimi vytvorené ZMAR štruktúry smerujú celú spoločnosť (k egopatokracii vyvolených debilizátorov, ktorí majú všetky výhody a všetku moc, bez akejkoľvek zodpovednosti za čokoľvek. A na druhej strane k miliónovým anonymným davom nimi sústavne debilizovaných ich “vol(ič)ov”, ktorí nemajú žiadne výhody, ani žiadnu moc a musia iba útrpne platiť všetok ich papalášizmus a znášať všetky ich zlé rozhodnutia aj keby to boli evidentné zlodejiny a podvody a to bez akejkoľvek reálnej šance na ich potrestanie, alebo aspoň ich odvolanie z funkcie).*
:::
