# A čo ďalej? Je toto všetko? Nedá sa štát organizovať nejako lepšie?

Určite dá. Štát a celá spoločnosť sa dá zorganizovať oveľa lepšie, ako si ju dnes organizujú ZMAR štruktúry, čo by si však vyžadovalo mnohé zmeny zákonov a Ústavy.

V predchádzajúcich kapitolách sme si uviedli, ako si občania môžu vybudovať vlastnú slobodnú organizáciu Kruhy, ktorú môžu mať pod kontrolu stále a prostredníctvom ktorej si môžu postupne celý štát a celú spoločnosť pretvoriť k svojmu obrazu, podľa svojho najlepšieho vedomia a svedomia.

::: {.word-note}
*Poznámka: T.j. nie tak, ako je to teraz, že volia nejakých od nich nijako nezávislých straníkov (alebo nezávislých), ktorí pred voľbami rozprávajú iné ako po voľbách, v jednej strane iné ako v druhej a jediné čo majú všetci spoločné, že nikto z nich nehovorí celú pravdu a to ani pred voľbami, ani po voľbách, iba všetci zamlčujú niečo iného, alebo krivia pravdu nejakým iným spôsobom. Väčšinou tak, ako sa im to práve najviac hodí. A spoločne zamlčujú a pod kobercec skrývajú prakticky všetko podstatné. A to, o čom rozprávajú a o čom sa medzi sebou na verejnosti hádajú sú prakticky iba nimi vymyslené nepodstatné bludy slúžiace najmä na emocionálne oblbovanie, debilizáciu a fanatizovanie ich obetí (ich tzv. vol(ič)ov).*
:::

Ak sa členom OK podarí získať väčšinu poslancov v parlamente pre svoje návrhy, budú môcť meniť zákony. Napr. preorganizovať samosprávu na miestnej úrovni a úrovni VÚC tak, aby im viac vyhovovala. Ak sa členom OK podarí získať aj ústavnú väčšinu poslancov v parlamente pre svoj návrh, môžu zmeniť celý štátny politický režim podľa svojho najlepšieho vedomia a svedomia.

To už bude závisieť od členov OK, čo budú chcieť a vedieť robiť. Môžu chcieť veci menšie, aj veci väčšie, aj veci najväčšie, ale iba ak pre svoje návrhy nájdu pochopenie a súhlas väčšiny ostatných. Nie je na nás, aby sme my, autori tohoto dokumentu určovali, čo by mali chcieť. Myslím, že v čase, keď k tomu príde, budú v OK členovia, ktorí budú vedieť lepšie, ako my dnes, čo by bolo najlepšie zmeniť a aj ako.

Napriek tomu tu uvedieme zopár vecí, len ako príklad n toho, čo by sa (podľa nášho najlepšieho vedomia a svedomia) mohlo zmeniť k lepšiemu (tu len bodovo, v inom dokumente podrobnejšie):

- Kompletná rekonštrukcia NRSR – zníženie počtu poslancov a zmena volebného systému vo voľbách do NRSR tak, že každý región (resp. pri regiónoch s väčším počtom obyvateľov subregión - časť regiónu) by si volil jedného priamo voleného (a odvolateľného) zástupcu/poslanca NRSR. Jednoducho každý región/subregión SR by mal v NRSR pre seba vyhradenú svoju 1 stoličku. Spôsob, akým si vyberie na ňu svojho zástupcu by bol v kompetencii obyvateľov daného (sub)regiónu, rovnako ako aj spôsob a čas jeho výmeny za niekoho iného.
- Úplná rekonštrukcia VÚC a prechod ich právomocí na historické/prirodzené regióny, ktoré sú bližšie k občanom. A s tým spojená úplná rekonštrukcia volebného systému do VÚC, resp. regionálnych parlamentov tak, aby si jednotlivé obce/mestské časti/municipality v regióne mohli zvoliť každá svojho (jedného) zástupcu/poslanca do regionálneho parlamentu a aby si ho mohli v prípade potreby/nutnosti/vôle kedykoľvek vymeniť.
- Zmena volebného systému v mestách a obciach tak, aby si každá časť obce/mesta volila jedného zástupcu/poslanca a mohla si ho teda aj kedykoľvek vymeniť (napr. prostredníctvom petície a referenda v okrsku daného poslanca). Zároveň aby títo takto zvolení a odvolateľní poslanci mohli kedykoľvek voliť a odvolať t.j. vymeniť starostu, alebo primátora, okamžite ak majú akékoľvek podozrenie z toho, že ten nerobí to čo by mal, alebo dokonca robí to, čo by nemal. A v prípade, ak je podozrenie, že primátor/starosta spravil niečo, čo bolo na škodu ostatným obyvateľom obce/mesta, tak ho okamžite vymeniť, aby sa to mohlo čím skôr vyšetriť, škody mohli byť minimalizované a vinník potrestaný.
- Sfunkčnenie referenda na všetkých úrovniach verejnej správy. Aj v okrsku miestneho poslanca, aj na miestnej úrovni, aj v okrsku regionálneho poslanca, aj v okrsku poslanca NRSR (t.j. na regionálnej/subregionálnej úrovni), až po celoštátnu úroveň a to tak, aby všetci občania mohli petíciou referendum vyvolať a referendom odvolať, alebo vymeniť, akéhokoľvek svojho zástupcu vo verejnej správe, ako aj zastaviť akékoľvek opatrenie, rozhodnutie, zákon, alebo nariadenie akéhokoľvek orgánu verejnej správy, ktoré by bolo v rozpore s tým, čo väčšina občanov považuje za správne a potrebné.
- Rekonštrukcia funkcie prezidenta (viď. poznámka v predchádzajúcej kapitola) de fakto prakticky zrušením tejto funkcie bez náhrady (resp. len s formálnou náhradou v podobe parlamentom vybraného ministra s reprezentatívnou funkciou prezidenta tak ako je tomu napr. vo Švajčiarsku. Prezidentské veto nahradiť všeľudovým referendom, pomocou ktorého by občania mali právo nie iba (v určenej lehote) vrátiť každý zákon do parlamentu/NRSR, ale ho definitívne referendom zamietnuť, ak by ho väčšina občanov nepovažovala za prínosný (a to na všetkých úrovniach, nielen celoštátnej, ale aj regionálnej a miestnej – viď. predchádzajúci bod) podobne, ako je to vo Švajčiarsku.

A mnoho ďalších potrebných vecí, ktoré sú však čím ďalej tým vzdialenejšie súčasnému systému/režimu resp. stavu súčasnej spoločnosti, a preto by boli stále ťažšie pochopiteľné, a možno dokonca boli aj za hranicou toho, čo je možné v tomto režime a v tomto stave spoločnosti napísať.

Nie je ale ani potrebné všetko tu podrobne písať, pretože by to bolo o.i. aj neúmerne dlhé. Tak či onak v čase, keď bude mať OK toľko členov, že budú môcť meniť tieto veci a členovia OK budú fungovať slobodne na základe princípov popísaných v tomto dokumente (a nie tak, ako dnes, t.j. ZMAR systémom), tak už aj sami budú vedieť, čo treba zmeniť a ako, ako by sme to tu teraz my mohli napísať. Tak či onak to bude závisieť od nich, čo budú chcieť, aké bude ich poznanie a rozlíšenie toho, čo je pre nich dobré a čo zlé, čo všetko si dokážu predstaviť a čo z toho aj zrealizovať.

Ale predsa ešte pre zaujímavosť napíšeme jednu z tých vecí, ktorá je už možno za tou hranicou dnes mysliteľného, ale predsa ju v nasledovnej kapitole uvedieme, ale len ako jeden z možných príkladov toho, čo by sa tu napr. okrem predchádzajúcich vecí, možno dalo spraviť lepšie (ako kdekoľvek inde vo svete. Viac o tom v inom dokumente “Lepšie štátne zriadenie pre Slovensko”):

## Prirodzené delenie občanov na mužov a ženy?

Aj keď sa to môže niekomu javiť ako triviálne, inému sa to zase môže javiť ako niečo nepochopiteľného, niekomu možno aj ako zbytočné, inému ako zásadné a niekomu možno aj ako škodlivé. To môže byť spôsobené rôznym stupňom poznania. Napriek tejto možnej kontroverzii to tu uvediem, ale len ako jednu možnosť, kuriozitu, alebo ako náčrt ďalšej možnosti ako narovnať spoločnosť aj nad rámec vecí uvedených v predchádzajúcej kapitole.

Ľudia ani občania nie sú rovnakí a to bez ohľadu na ideológie, ktoré vytvorili pojem občan. Tieto ideológie nezohľadňujú ani do očí bijúce rozdiely medzi ľuďmi, nieto ešte tie subtílnejšie. Všetkých zmiešavajú do jedného abstraktného pojmu občan. Tým akoby miešali jablká s hruškami a možno aj iným “ovocím“… Spoločný menovateľ všetkých týchto však prakticky neexistuje (a je to teda dosť vyprázdnená množina). A preto aj pojem občan, na ktorom stojí, ale skôr upadá aj táto tzv. liberálna demokracia je taký vyprázdnený.

Prečo? Miešať všetko a všetkých dohromady nie je znakom ani vysokej inteligencie, ani vysokej kultúry, ani vysokého poznania. A to je jeden z principiálnych omylov súčasnej spoločnosti, ktorý nie je vyriešený, je prehliadaný (prípadne ZMAR štruktúrami riešený úplne perverzne/zvrátene) a spôsobuje v spoločnosti množstvo problémov, ktoré sú však už tak zakorenené, že ich väčšina berie ako nevyhnutné zlo. A to napriek tomu, že aj kvôli nemu táto civilizácia možno skôr či neskôr zanikne.

Problémom je tu ignorovanie zo strany ZMAR inštitúcií, ideológií a celého spoločenského zriadenia tej pravdy, že ľudia nie sú rovnakí. Ignorovanie aj toho, čo je zjavné, zrejmé a prirodzené, t.j. že ľudia sa prirodzene delia, minimálne na dve skupiny, ktoré by mal dokázať rozlíšiť každý: na mužov a ženy, ktorí prirodzene majú (a aj by prirodzene mali mať) rozdielne vlastnosti, schopnosti, danosti, silné a slabé stránky atď. Muži a ženy nie sú rovnakí a ani by nemali byť rovnakí.

Celá sústava štátnych a verejných inštitúcií však bola vytvorená mužmi a pre mužov v časoch, kedy sa so ženami vôbec nepočítalo, že by sa mali akokoľvek účastniť verejného života. Ani ako voličky, nieto ako volené funkcionárky, poslankyne, starostky, ministerky a pod…

Aj keď neskôr bolo ženám umožnené voliť a byť volené, nebolo im v štátnej a verejnej správe vytvorené miesto, kde by mohli pestovať svoje ženské kvality a vlastnosti, ženskú polovicu kultúry a politiky. Museli sa iba prispôsobiť už existujúcemu mužskému svetu v existujúcich inštitúciách. (A naopak muži sa museli prispôsobiť ženským voličkám a ženskej konkurencii atď...). Miesto toho, aby sa pestovala a kultivovala mužská a ženská kultúra, mužské a ženské energie vo svojich vlastných kvalitách, sa týmto pomiešaním v spoločnosti neustále vytvára stále väčší mačkopes.

Členovia OK však tomu môžu predchádzať, ak chcú a vidia v tom zmysel a prínos tým, že rozdelia svoje kruhy na mužské a ženské (tak ako to bolo navrhované na konci kapitoly [Aký je rozumný počet členov kruhu?](#word-optimalny-pocet-clenov)). Toto môžu robiť na všetkých stupňoch kruhov, od 1. stupňa svojich kruhov až po stupeň posledný. Takto môžu vzniknúť vlastne prakticky dve samostatné organizácie – mužská OK a ženská OK, ktoré budú síce navzájom oddelené, ale navzájom previazané a prepojené cez prirodzené neformálne vzájomné vzťahy prostredníctvom prakticky všetkých členov OK.

Takto môžu mať ženy svoje samostatné kruhy a to na všetkých stupňoch, v ktorých sa nemusia prispôsobovať mužským témam, mužským energiám atď. Môžu mať svoje bezpečné miesto, kde im muži nekonkurujú, kde ich neutláčajú, neobmedzujú atď. Všetkým týmto problémom sa vyhnú a môžu sa oslobodené od tohto všetkého sústrediť na to, čo je pre nich podstatné v čom oni vidia najväčší zmysel.

To isté v mužských kruhoch, tiež na všetkých stupňoch, v ktorých sa zas nemusia muži prispôsobovať ženským témam a ženským energiám atď. a môžu sa slobodne sústrediť na to, čo je pre nich podstatné.

Takto sa v OK prakticky úplne eliminujú konflikty, súťaživosť a rivalita medzi mužmi a ženami. Napr. aj tá otázka či bude kruh zastupovať muž, alebo žena. Každý ženský kruh bude prirodzene zastupovať nejaká žena a každý mužský kruh nejaký muž.

Podobne by sa aj štátne aj verejné inštitúcie dali vylepšiť tým, aby umožnili, aby sa v nich ženy aj muži mohli realizovať bez toho, aby si navzájom konkurovali, bojovali medzi sebou o moc a navzájom sa ovplyvňovali a obmedzovali.

Napr. na úrovni miestnej samosprávy v obciach a mestách by mohli byť samostatné zastupiteľstvá, jedno pre ženy a druhé pre mužov. Ženy v meste/obci by si volili svoje zástupkyne do ženského zastupiteľstva a muži do mužského zastupiteľstva. Počet týchto zástupcov dohromady by mohol zostať rovnaký ako dnes, takže by to nestálo nič naviac.

Kompetencie zastupiteľstva by si mohli rozdeliť tak, aby mužské aj ženské zastupiteľstvo malo svoje vlastné kompetencie a svoje vlastné rozpočty na ktorých by sa medzi sebou dohodli. Ženské kompetencie by mohli byť napr. predškolské zariadenia, dievčenské školy/triedy na prvom a druhom stupni, dievčenská a ženská kultúra a šport, zdravotníctvo, pracovné a sociálne oblasti, životné prostredie a pod.

Tieto oblasti by malo vo svojej výlučnej kompetencii ženské zastupiteľstvo. Mužské zastupiteľstvo by zas malo vo svojej výlučnej kompetencii mužské kompetencie ako napr. chlapčenské školy-triedy na prvom a druhom stupni, chlapčenský a mužský šport a kultúru, mestskú políciu, hasičov, dopravu, energetiku, komunikácie a pod. Tak, ako by sa na rozdelení kompetencií spolu dohodli.

Muži v obci/meste, resp. mužské zastupiteľstvo by volilo svojho starostu/primátora a ženy resp. ženské zastupiteľstvo svoju starostku/primátorku. Títo by mali každý svoje vlastné kompetencie v daných oddelených oblastiach a boli na čele svojej časti úradu a svojich úradníkov/úradníčok. Realizovali by každý svoje vlastné kompetencie, starosta/primátor pod kontrolou mužského zastupiteľstva a starostka/primátorka pod kontrolou ženského zastupiteľstva.

Starosta/primátor by teda reprezentoval celú mužskú časť obce/mesta a starostka/primátorka ženskú časť obce/mesta. Celé mesto/obec by reprezentovali zvolený primátor s primátorkou (resp. zvolený starosta so starostkou).

Podobne by to mohlo byť aj na regionálnej úrovni aj na celoštátnej úrovni:

Parlament/NRSR by bol dvojkomorový/á. Jedna komora mužských zástupcov/poslancov a druhá komora ženských zástupkýň/poslankýň. Kompetencie aj jednotlivé ministerstvá by boli rozdelené medzi obe komory parlamentu tak, aby každá komora parlamentu, či už ženská, alebo mužská mohla nezávisle rozhodovať o veciach vo svojej výlučnej kompetencii.

Možné rozdelenie ministerstiev by mohlo byť napr. takéto:

- Ženské
    - Ministerstvo zahraničných vecí
    - Ministerstvo životného prostredia
    - Ministerstvo ženského vzdelávania, výchovy, vied a výskumu
    - Ministerstvo ženskej kultúry a športu
    - Ministerstvo financií ženských rezortov
    - Ministerstvo sociálnych vecí a práce
    - Ministerstvo zdravotníctva a prevencie chorôb
- Mužské
    - Ministerstvo obrany a civilnej ochrany
    - Ministerstvo vnútra, polície a spravodlivosti
    - Ministerstvo mužského vzdelávania, výchovy, vied a výskumu
    - Ministerstvo mužského športu a kultúry
    - Ministerstvo financií mužských rezortov
    - Ministerstvo hospodárstva, pôdohospodárstva a rozvoja vidieka
    - Ministerstvo dopravy, energetiky, komunikácií, výstavby a regionálneho rozvoja

Ženská komora NRSR/parlament-u by volila ministerky na ženské ministerstvá a prezidentku SR. Mužský parlament by volil ministrov na mužské ministerstvá a prezidenta SR. Prezidentka SR by reprezentovala všetky ženské ministerstvá a ministerky, ženskú komoru NRSR/parlament-u, všetky ženské štátne a verejné inštitúcie SR ako aj všetky ženy a dievčatá v SR. Prezident SR by reprezentoval mužské ministerstvá a ministrov, mužský parlament/NRSR, mužské štátne a verejné inštitúcie ako aj všetkých mužov a chlapcov v SR. Celú SR by reprezentovali obaja spoločne (napr. pri podpise medzinárodných záväzkov v mene všetkých občanov – mužov aj žien).

::: {.word-note}
*Poznámka: A všetko toto by mohlo stáť oveľa menej, ako dnes. Prečo? Napr. bola by síce aj slovenská prezidentka aj prezident, takže dvaja miesto jedného, ale touto funkciou by boli iba poverení jedna/najlepšia ministerka a jeden/najlepší minister. Takže v skutočnosti miesto jedného prezidenta a každoročne desiatok miliónov EUR nákladov na jeho prezidentskú kanceláriu by to nestálo prakticky nič, alebo skoro nič. A to ani na voľby prezidenta. T.j. náklady na prezidenta by sa takto dali zmenšiť rádovo možno 100x, alebo viac, napriek tomu, že by boli dvaja a napriek tomu, že ich kvalita aj kvantita odvedenej práce by zrejme boli úplne inde ako dnes, pretože by to boli zrejme jedni z najkvalifikovanejších ľudí v SR.*
:::

::: {.word-note}
*Počet členov ženskej a mužskej komory parlamentu/NRSR sumárne by mohol byť menší, ako dnešných 150 poslancov. Ak by každá komora parlamentu mala v kompetencii napr. horeuvedených 7 ministerstiev, a každé ministerstvo by v parlamente kontroloval napr. kruh 7-mich poslancov/poslankýň, takže celkovo by v každej komore parlamentu mohlo byť napr. 7x7=49 poslancov. T.j. dohromady 49 poslancov v mužskej komore + 49 poslankýň v ženskej komore parlamentu = 98 zástupcov v celej NRSR/parlamente. Oboch komorách Slovenského snemu.*
:::

::: {.word-note}
*Aj ministerstiev by bolo menej ako je dnes, ale najmä mohli by fungovať oveľa efektívnejšie, keby sa tranformovali tiež na systém Kruhov OK (a neboli riadené súčasným ZMAR systémom). A potom by sa nižšie náklady na tieto ministerstvá, ale najmä ich vyššie výkony nemuseli zlepšiť o percentá, alebo desiatky percent, ale možno aj rádovo ako napr. pri tej funkcii prezidenta. (Aj keď pri funkcii prezidenta je ten pomer cena/výkon resp. efektivita asi najväčší extrém, aký v SR vytvorili - [viď. poznámka pod čiarou](#word-prezident)).*
:::
