# Dodatky a diskusia?

## Paralelné/alternatívne štruktúry OK sú tiež OK?

V prípade veľkého počtu členov OK je ich názorová nejednotnosť prirodzená. Nemôžu mať všetci na všetko rovnaký názor. Dokonca ani na jednu vec nebudú mať zrejme všetci rovnaký názor. A nie je to ani potrebné. Naopak. Je vždy lepšie mať viacero rôznych, podľa možností čo možno najlepších a najprepracovanejších riešení na každý problém a môcť si z nich podľa situácie v danom čase a mieste, kedy a kde problém vznikne, vybrať to najvhodnejšie riešenie, ako mať mnoho problémov na ktoré nie sú žiadne dobré riešenia tak, ako je tomu dnes.

Preto napr. v Celoslovenskom hnutí OK je možné, a môže byť aj výhodné a potrebné, aby členovia OK vytvárali v rámci OK paralelné štruktúry nielen k existujúcim štátnym inštitúciám (ako napr. ministerstvám, zastupiteľstvám na všetkých úrovniach a pod.), ale v prípade ak existuje dostatok členov OK, ktorí by chceli vytvárať aj ďalšie alternatívne štruktúry a koncepty aj k týmto paralelným štruktúram tak vytvárali aj tieto. Napr. ak chcú pracovať na alternatívnych odborných koncepciách, alebo riešeniach v rámci OK.

Takto je možné vytvárať v rámci OK štruktúru kruhov tvoriacu agendu napr. nejakého ministerstva a popritom rozvíjať a pracovať aj na nejakej alternatívnej koncepcii daného ministerstva. Napr. ak sa iba časť členov odborného kruhu nejakého ministerstva stotožní s nimi vytváranou koncepciou, a iní členovia tohto odborného kruhu majú iný odborný názor na to, vôbec na základe akých princípov by mala byť táto koncepcia tvorená, tak miesto toho, aby navzájom medzi sebou zvádzali boj v tomto jednom odbornom kruhu o to, ktorá z týchto principiálne rôznych koncepcií sa viac premietne do aktuálne nimi vytváraného programu ministerstva, a vytvárať tak spolu nejakého mačkopsa, miesto toho je lepšie tento odborný kruh rozdeliť a pracovať oddelene na dvoch nezávislých koncepciách v inom (aj keď možno menšom kruhu spolupracovníkov), ktorí chcú rozpracovávať, konkretizovať a potom medzi členmi OK propagovať túto inú alternatívnu koncepciu.

Ktorá koncepcia bude kedy použitá bude závisieť od toho, ktorá viac osloví členov OK v čase, keď sa bude treba pre nejakú vypracovanú koncepciu rozhodnúť. To môže byť v čase zverejnenia programu pred voľbami, alebo v čase voľby nového ministra po voľbách, alebo aj kedykoľvek počas volebného obdobia napr. ak by sa v praxi ukázali nedostatky aktuálneho programu OK, alebo napr. ak by sa zmenili podmienky tak, ako predpokladala jedna z koncepcii a iná nie.

Preto ak má v OK nejaký člen návrh na nejakú lepšiu koncepciu čohokoľvek, čo sa v spoločnosti deje, tak najlepší čas na jej formulovanie je čím skôr. Či už v kruhu členov, v ktorom je daný člen členom, alebo v nejakom inom kruhu napr. ním vytvorenom.

[]{#word-preco-su-potrebni}

## Prečo sú potrební zástupcovia kruhov?

Efektívna komunikácia, resp. výmena informácií medzi jednotlivými členmi a kruhmi je tiež forma práce (a možno aj umenia a vedy), ktorá vyžaduje ľudské schopnosti, čas a energiu. T.j. cenné ľudské zdroje s ktorými je treba šetriť. Komunikačný šum, napr. klebety, bulvár, ZMAR politika... , alebo každé nekonštruktívne tliachanie o veciach, ktoré členovia kruhu buď nemôžu ovplyvniť, alebo sa netýkajú ich aktivít, alebo ich nezaujímajú, obťažujú tých, ktorí by miesto počúvania niečoho, čo ich nezaujíma, radšej diskutovali niečom, čo ich zaujíma a čo môžu ovplyvniť.

Preto je potrebné diskusiu viesť tak, aby k niečomu smerovala, plané reči obmedzovať, filtrovať to podstatné a nepodstatným rečiam pokiaľ možno predchádzať. To je úlohou všetkých členov kruhu, ale najviac ich zástupcov, pretože tí komunikujú nielen v kruhu, ktorý zastupujú, ale aj v kruhu na vyššom stupni.

Ich úlohou je sumarizovať to podstatné, čo sa prebralo v kruhu, ktorý zastupujú a stručne o tom podstatnom informovať členov v kruhu vyššieho stupňa. A naopak o podstatných veciach toho, čo sa prebralo a dohadovalo v kruhu vyššieho stupňa stručne a výstižne informovať členov kruhu, ktorý si ich zvolil za svojho zástupcu.

S počtom členov v organizácii rastie exponenciálne počet vzájomných potenciálnych vzťahov medzi nimi. Preto so zväčšujúcim sa počtom členov je potrebné sa rozdeliť do väčšieho počtu skupín/kruhov, inak by boli všetci vystavení a zaťažení exponenciálne rastúcim komunikačným šumom, nedorozumeniam a konfliktom všetkých ostatných. A to by zrejme už pri neveľkom počte členov, narazilo na ľudské, časové, emočné aj mentálne limity väčšiny z nich a celú organizáciu by to znefunkčnilo a nakoniec viedlo k jej rozpadu.

Preto je efektívna komunikácia jeden z najzávažnejších a teda aj najviac limitujúcich problém pre každú väčšiu spoločnosť a teda aj celé ľudstvo. K riešeniu tejto kritickej úlohy musia prispieť všetci členovia všetkých kruhov, najmä však ich zástupcovia, ktorých to je prvoradá úloha.

Zástupcovia majú za úlohu stručne a jasne formulovať to, na čom sa členovia kruhu dohodli. Na čom panuje zhoda. T.j. napr.

- Zástupca kruhu na 2.stupni by mal vedieť formulovať, čo chce ~10 členov kruhu, ktorý zastupuje.
- Zástupcu kruhu na 3.stupni by mal vedieť formulovať, čo chce ~100 členov kruhov 1. a 2. stupňa, ktorých zastupuje.
- Zástupcu kruhu na 4.stupni by mal vedieť formulovať, čo chce ~1000 členov kruhov 1., 2. a 3. stupňa, ktorých zastupuje.
- Atď.

Členovia OK v kruhov 1. stupňa síce nezastupujú iných členov OK, ale môžu zastupovať nečlenov OK, ako napr. svoju rodinu, priateľov a atď. Aj ten kto nemá, alebo nechce v kruhoch zastupovať nikoho iného okrem seba, ani svoju rodinu, priateľov atď., aj o tom môžeme povedať, že niekoho v kruhoch predsa len zastupuje. Buď svoje vlastné ego, alebo v lepšom prípade hlas svojho vlastného vedomia a svedomia (vo védach zvané átman – to večné v človeku).

Preto o všetkých členoch OK je možné povedať, že sú aj členovia aj zástupcovia. Iba rôzneho stupňa. Niekto zastupuje iba seba, niekto aj svoju rodinu, alebo iných ľudí, niekto zastupuje celý kruh členov OK, ktorí si ho vybrali za svojho zástupcu atď. A toto sa však v čase stále mení, na každom stretnutí sa to môže meniť. Preto aj označujeme jednotlivé kruhy ako kruhy 1. stupňa, 2. stupňa, 3. stupňa atď.

- Každý člen kruhu 1. stupňa zastupuje v kruhu seba, prípadne aj členov svojej rodiny, priateľov, alebo iných nečlenov OK.
- Každý člen kruhu 2. stupňa zastupuje členov kruhu 1. stupňa, ktorí si ho vybrali za svojho zástupcu.
- Každý člen kruhu 3. stupňa zastupuje členov kruhu 2. stupňa, ktorí si ho vybrali za svojho zástupcu.
- Atď.

[]{#word-preco-kruhovo-sietovo-spatno-vazobn}

## Prečo kruhovo-sieťovo-spätno-väzobne-ahierarchická organizácia?

Tento názov by bol pre OK asi príliš dlhý na zapamätanie , ale pomenováva viaceré princípy Kruhov:

- Kruhová – členovia sa organizujú v kruhoch, čím sa chce vyjadriť princíp, že všetci členovia v kruhu sú si medzi sebou rovní. T.j. všetci v kruhu sú navzájom vo vzťahu rovný s rovným (t.j. (slobodný) človek <-> (slobodný) človek). V kruhu nie je potrebné, ani žiadúce, aby boli medzi ľuďmi vzťahy založené na moci človeka nad človekom t.j. vzťahy typu pán -> poddaný, nadriadený -> podriadený, vyvolený -> nevyvolený a pod. Slobodné rozdelenie členov OK do jednotlivých kruhov umožňuje, vďaka týmto relatívne malým, pružným (tekutým) kolektívom, efektívnu činnosť nielen jednotlivých kruhov ale aj celej OK.
- Sieťová – členovia OK môžu byť členmi vo viacerých kruhoch a tým vytvárajú prepojenia medzi týmito kruhmi. Tým vzniká medzi kruhmi sieť. Niekto je napr. členom miestneho hruhu v mieste v ktorom býva a okrem toho je členom nejakého záujmového kruhu, napr. kruhu IT-čkarov, ktorí riešia IT podporu členom OK a tým tvorí prepojenie medzi týmito kruhmi, ktorých je členom. Alebo ak chcú napr. nejaké susedné kruhy spolu intenzívnejšie spolupracovať na nejakých spoločných aktivitách, môžu sa prepojiť napr. prostredníctvom nejakého svojho člena, ktorého členovia daného kruhu vyšlú s nejakým návrhom ako svojho vyslanca/zástupcu do kruhu s ktorým chcú spolupracovať.
- Spätno-väzobná preto, že vždy existuje možnosť priamej spätnej väzby medzi všetkými členmi v kruhu. T.j. zástupcovia kruhu, ktorí sú kruhmi volení, alebo poverení, sa zároveň kruhu zodpovedajú a môžu byť na ktoromkoľvek stretnutí dopytovaní, konfrontovaní, prípadne vymenení, odvolaní, alebo dokonca vylúčení z kruhu tak, ako ktorýkoľvek iný člen kruhu. Dôležité pritom je, že táto možnosť spätnej väzby je priama, bezprostredná a s okamžitou platnosťou. T.j. tí, ktorí svojho zástupcu kruhu na ktoromkoľvek svojom stretnutí zvolili, sa ho môžu aj na ktoromkoľvek stretnutí čokoľvek opýtať, alebo ho aj vymeniť, alebo vylúčiť a to priamo, bez akýchkoľvek prostredníkov, alebo akýchkoľvek formalít, a ich rozhodnutie je okamžite platné. Neexistuje teda žiadne volebné obdobie, v ktorom by “vyvolení” zástupcovia boli neodvolateľní a mohli si robiť čokoľvek čo chcú, a ostatní z kruhu to museli strpieť.
- Ahierarchická – okrem náhodného (ad-hoc) sieťovania kruhov členmi kruhov sú všetky kruhy navzájom prepojené aj pomocou dobre definovanej „ahierarchickej“ štruktúry tzv. kruhov „vyššieho“ stupňa. Prečo? Pretože tak sa tvorí minimálna štruktúru prepojení medzi kruhmi tak, aby organizácia tvorila jeden funkčný celok, t.j. aby boli všetky kruhy navzájom prepojené minimálnym počtom spojení, t.j. najefektívnejšie. Takáto “ahierarchická“ štruktúra je orientovaná opačne ako tzv. hierarchická, v ktorej moc pôsobí z hora dole. Ako napr. v RKC, súkromných korporáciách, armádach, štátoch, atď. V OK to tak nie je, t.j. volení zástupcovia kruhu nie sú “nadriadení” členom kruhu, ktorí si ich zvolili, pretože títo ich majú možnosť kedykoľvek vymeniť. A to aj bez dôvodu. T.j. v kruhu nie je jeden “nadriadený” zástupca a ostatní členovia kruhu jemu “podriadení”, ale je to skôr naopak, t.j. zástupca kruhu sa musí riadiť tým, čo chcú členovia kruhu, ktorých zastupuje, inak zrejme nebude dlho trvať, kým bude na návrh niektorého člena kruhu vymenený za nejakého iného člena kruhu. A tento princíp platí v každom kruhu na všetkých stupňoch.
    - *Poznámka 1: Tento princíp sme kvôli odlíšeniu od hierarchie nazvali “ahierarchický“, aj keď to možno nie je úplne presný názov. Prečo? Zvolili sme ho preto, že má vyjadriť opak toho, čo je momentálne vnímané ako hierarchia. Presnejšie by však možno bolo nazývať historické chápanie hierarchie ako “hierarchia moci uplatňovaná zhora dole” (alebo hierarchia moci smerujúca dole) a miesto termínu “ahierarchia“ používať termín „hierarchia moci uplatňovaná zdola hore“ (alebo hierarchia moci smerujúca hore). Keďže ale nemôžeme predefinovať už zavedené a všeobecne nejako používané a chápané termíny a keďže pod pojmom “hierarchia” väčšina zrejme myslí “hierarchia moci uplatňovaná zhora dole” (t.j. hierarcha moci smerujúca dole), tak sme navrhli nazývať opačne smerujúcu hierarchiu použitú v OK t.j. “hierarchiu moci uplatňovanú zdola hore” (t.j. hierarchiu moci smerujúcu hore) ako “ahierarchiu”. T.j po slovensky “bez hierarchie”, “ne-hierarchia”.*
    - *Poznámka 2: Presnejšie povedané sa ale nejedná ani o typickú hierarchiu ani o opak hierarchie, pretože v OK nie sú členovia kruhov mocensky “podriadení” im zvoleným zástupcom, ale ani ich zástupcovia nie sú mocensky “podriadení” členom kruhov, ktorí ich volili. Prečo? Pretože všetci členovia OK by sa mali riadiť svojim najlepším vedomím a svedomím, t.j. byť slobodní v tom čo robia. Aj členovia aj zástupcovia kruhov, ktorí sú tiež členovia OK. Preto ak by členovia kruhu chceli nútiť svojho zástupcu robiť niečo, čo on sám nechce (napr. niekde niečo navrhovať, dohadovať, čo je mu proti srsti), tak to riadiac sa svojim najlepším vedomím a svedomím zrejme odmietne robiť a členovia kruhu to budú musieť akceptovať, alebo si zvoliť za svojho zástupcu niekoho iného (ak to niekto chce robiť). Preto napr. nemá zmysel kresliť zástupcu kruhu nad kruhom, ale ani pod kruhom. Skôr ho má zmysel kresliť v  stredu kruhu, ako takú os kruhu, stred názorov, záujmov a potrieb členov kruhu, cez ktorého je daný kruh prepojený s inými kruhmi v OK ako kolečká vo veľkom stroji.*
    - *Poznámka 3: Preto tzv. “vyššie” stupne kruhov v skutočnosti nesmerujú zástupcov ani nad ostatných členov, ani pod ostatných členov. Smerujú ich skôr “do stredu” OK (k pravde, chce sa mi napísať...) TODO: Preto tie obrázky by som mal prekresliť tak, aby kruh “na najvyššom stupni“ nebol kreslený na obrázku hore, ale v strede obrázku a tie kruhy „nižších stupňov“ boli kreslené okolo neho a tvorili stále väčšiu sústavu sústredných kruhov. A to tak, že každý nižší stupeň by bol ďalej od stredu, všetky kruhy spoločne tvoriace stále väčší kruh (v 2D), resp. guľu, ak by sa to nakreslilo priestorovo v 3D. A úplne najpresnejšie povedané by celé OK, ak by sa nakreslilo priestorovo, tak by vytváralo niečo ako ľudský mozog, pretože optimálne by bolo, ak by to malo dve oddelené časti mužskú a ženskú časť, tvoriacu dve polo-gule – dve hemisféry, jednu mužskú a druhú ženskú).*

## Duchovné prebudenie a znovuzrodenie Človeka v Kruhoch?

Božskú iskru/ducha/boha/átmana má každý človek v sebe, vo svojom vedomí a svedomí a preto každá snaha podriadiť človeka a jeho myslenie akejkoľvek vonkajšej moci, ideológii, alebo maspropagande, je v skutočnosti snahou proti pravde, proti všemíru, proti Bohu a proti Človeku.

Preto je potrebné, aby sa v Kruhoch všetci členovia rozhodovali vo všetkom sami a slobodne podľa svojho vlastného najlepšieho svedomia a vedomia vždy tak, ako oni svojim vlastným cítením, vnímaním, svedomím, vedomím a rozumom pokladajú za najsprávnejšie pre všetkých. Aby sami hľadali pravdu v každej veci. Takto najrýchlejšie dospejú k svojmu čo najväčšiemu prebudeniu a osvieteniu v každej veci, čo je jedným zo zmyslov života človeka.

Najlepšie podmienky na prebudenie človeka do svetla čo najlepšieho poznania nastanú vtedy, keď sa obklopí ľuďmi, ktorí tiež slobodne, z vlastnej vôle a úprimne hľadajú pravdu v každej veci, ktorú riešia. Tú pravdu, božskú iskru, ktorú má každý v srdci, len si ju uvedomiť. A nenechať ju vyhasnúť, ale naopak ju stále viac rozkresávať a rozhojňovať.

Ak sa niekomu podarí nejakú tú pravdivú iskru pravého poznania pravdy zo seba vykresať, aj keď nedokonale, v kruhu iných, ostatní z nej môžu pomôcť vytvoriť väčší plamienok poznania. Ten prinesie viac svetla aj iným členom kruhu a prostredníctvom vyslancov/zástupcov kruhu aj iným kruhom. Takto sa z kruhu tento plamienok môže preniesť aj na iné kruhy, ich členovia tento plamienok môžu ešte zdokonaliť, rozjasniť a zväčšiť a nakoniec z neho celé Kruhy môžu vytvoriť tak veľkú vatru, ktorá rozžiari celú spoločnosť a prinesie do nej dostatok pravého svetla poznania a tepla spolupatričnosti pre všetkých.

Takto sú jednotlivé kruhy ako polienka vo vatre usporiadané zdola nahor v jednotlivých stupňoch. Duchovné idei, nápady, návrhy, svetielka poznania členov kruhov, vznikajúce v ktoromkoľvek kruhu/polienku, vyslanci/zástupcovia kruhov neustále roznášajú ako iskry vo vatre do ostatných kruhov/častí vatry z dola nahor a naopak a postupne nimi stále viac zväčšujú a rozžarujú kruhy tak, aby mohla celá vatra, celé Kruhy žiariť čo najviac svetlom pravého poznania a teplom vrúcnej spolupatričnosti pre všetkých.

## Oslovenie Slovӕnov?

::: {.word-note}
*Poznámka: V tejto kapitole používame tieto skrátené výrazy (a skratky):*
:::

- *“Kruh prvého stupňa“ 	= prvý kruh 	= 1.kruh*
- *“Kruh druhého stupňa“ 	= druhý kruh 	= 2.kruh*
- *“Kruh tretieho stupňa“ 	= tretí kruh	= 3.kruh*
- *Atď.*

Väčšinu toho, čo ľudia kedy spravili väčšieho, významnejšieho a trvalejšieho, tak nebolo vďaka výnimočným výkonom jednotlivcov, ale vďaka vzájomnej spolupráci - že sa dokázali spolupracovať, spolu sa organizovať. Či už pri tvorbe, udržiavaní, alebo pri obrane nejakých duchovných, kultúrnych alebo hmotných hodnôt, aby im to nejaká iná cudzia organizovaná skupina ľudí nescudzila, nezničila, alebo nepohanila.

Okrem rozvíjania poznania každého jedného človeka je preto podstatná aj spoločná organizácia ľudí, vďaka ktorej dokážu slobodne spolu-pracovať vo svojich aktivitách a tvorení hodnôt či už duchovných, kultúrnych, alebo hmotných. A následne ich rozvíjať a ochraňovať. A popri tom sa aj spoločne rozvíjať.

Práve nedostatočná schopnosť spolupráce a organizovania sa vo väčších počtoch bola a je achillovou pätou nás Slovӕnov, Slov-enov, Slov-anov, Slov-änov, Slov-ienov... (pozn. -ák je česká hanlivá prípona, ktorú preto nepoužívame).

Dlhú dobu sme žili sebestačne v malých skupinkách – občinách, mierumilovne a teda len v malých skupinkách, napr. občinách bez potreby organizovania sa do veľkých počtov, ako napr. armád. A keď tá potreba nastala zoči voči hrozbe vojensky zorganizovaným mnohopočetným hordám koristníkov, bolo už neskoro a preto sme boli neraz ovládnutí, okradnutí, zotročení, pohanení, vykorisťovaní, znásilňovaní...

Cudzorodí kriváci, otroci nám cudzej, nepriateľskej otrokársko/otrockej chtonickej ideológie, či už z ríše východorímskej, západodorímskej, franskej, germánskej... atď. boli zorganizovaní vo veľkých počtoch, ako zločinecké bandy, sekty, alebo mafie pomocou zhora mocou ako armáda (ZMAR) s cieľom egoistického prospechu tých, ktorí ich zhora riadili, na úkor všetkých ostatných. Jedna vláda, alebo panovník, cár, pápež, jedna ideológia, jedna strana, jedno náboženstvo, jeden egoizmus proti všetkým ostatným.

Aj keď medzi sebou títo prospechári, kriváci a egopati viedli mnohé boje o moc, panovníctvo, následníctvo trónu... (a vedú dodnes), ale aj tak ZMAR organizácie boli a sú oveľa mocnejšie ako my, všetci ostatní, pretože veľký počet ľudí je takto organizovaných. A preto zvíťazili a dodnes majú nad nami navrch. A preto nám dodnes mnohé ich chápadlá moci vládnu.

Slobodu-milovným Slovӕnom nebol spôsob ZMAR vlastný. Zhora mocou riadenie podobné talianskej mafii, v ktorej ľudia musia poslúchať vyššie postavených v hierarchii, poslúchať nejakého nadriadeného a podriaďovať sa mu len z titulu jeho funkcie a kriviť sa pred ním a poslúchať jeho neraz pokrivené príkazy im bolo proti srsti. Slobodu-milovní Slovӕni preferovali vlastné slobodné poznávanie a hľadanie pravdy pred cudzou vnucovanou dogmou a rozkazom. Prirodzene rešpektovali iba toho, kto si u nich svojou múdrosťou získal prirodzenú autoritu, na základe ich vlastného posúdenia jeho schopností. Nie nejakého vyvoleného, alebo z vrchu dosadeného funkcionára.

Tým, že sa naši predkovia snažili žiť čo najviac sebestačne a celá občina bola prakticky úplne sebestačná, tak ani nepotrebovali organizáciu väčšieho počtu ľudí, ako koľkí boli v občine. Nad-občinovú organizáciu buď ani nemali, alebo ak mali, tak jej moc a aj autorita bola slabá, pretože v bežnom mierovom živote Slovӕna prakticky nebola potrebná. Pre v bežnom mierovom živote nepotrebu vyššej nadobčinovej spolupráce, a teda aj jej faktickú neexistenciu počas väčšiny našej predkresťanskej minulosti, sme boli v minulosti ovládnutí ZMAR hordami bojovných, ľstivých a falošných kriváckych egoistických cudzákov bažiacich po moci nad všetkými a všetkým, celým svetom.

Cesta ako z toho von je iba v poznaní a pochopení podstaty tejto duchovnej pravdy. Pravdy o troch prútoch (alebo skôr tristo miliónov prútoch?). Ako sa hovorí, pravda človeka oslobodí.

Treba plne pochopiť, že bez spolupráce a našej vlastnej samoorganizácie sa, je každý z nás (a teda aj všetci dohromady), bez ohľadu na to, aký je kto prebudený, nadaný, alebo silný, prípadne bohatý, sám je iba ako steblo trávy, ktoré si každý lepšie a teda mocnejšie zorganizovaný kmeň, náboženská cirkev, alebo sekta, politická strana, alebo inštitúcia časom ohne alebo pristrihne, ovládne, okradne, prípadne aj zmanipuluje, pokriví, znásilní a pohaní tak, ako im to bude vyhovovať. A to tým viac, čím väčšiu majú moc a čím väčší sú to kriváci.

Môžu sa nám nepáčiť ich krivácke výpravy, ničenie našich krajín a národov, ich bezduchá nenávisť, suprenacizmus vyvolených krivákov, ich kriminalita, pokrytectvo, pretvárka, lži, ich lživé ideológie ktoré šíria vo svojich lživých masmédiách a inde. Oni sa nás ale nemajú dôvod pýtať na náš názor. Pre nich sme iba ako tráva, ktorá si možno šumí, šomre, ale ohýbať sa aj tak musí tak, ako ich vietor moci odniekadiaľ z ďalekej cudziny fúka. A to preto, že na rozdiel od nás sú zorganizovaní. Ako ZMAR a neraz aj tajne, falošne, pokrytecky a s pretvárkou, ale sú.

Oni, tí zorganizovaní, si robia u nás to, čo chcú a tak ako to chcú. To čo im vyhovuje a my, ktorí nie sme zorganizovaní, si môžeme myslieť a rozprávať čo chceme. Či sa nám to páči, alebo nie, všetci slúžime ich cieľom, my ich platíme, či už priamo, priamymi daňami, alebo nepriamo nepriamymi daňami, alebo nás okrádajú cez infláciu, cez zisky ich korporácií atď., atď., atď. Robia si tu to, čo im vyhovuje, klamú a kradnú, alebo si rovno tlačia peniaze vo veľkom a kvantitatívne, keď ich potrebujú na platenie hord svojich agentov a žoldnierov, zástupy ich bezduchých prisluhovačov, opakovačov ich lží, obhajcov ich podvodov a realizátorov ich zločinov.

A tak to bude dokým sa aj my nejako nezorganizujeme a sami si to nespravíme nejako lepšie.

Ako sa ale zorganizovať tak, aby mohli všetci zostať duchovne slobodní a rovní a nemuseli sa kriviť pred falošnými zhora dosadzovanými pasákmi a krivákmi, agentmi cudzích záujmov? Aby to časom neskončilo ako to ich “bahno“: ZMAR hierarchia ovládaná zločincami, ktorým sa musia podrobiť všetci, ktorí sú pod nimi. A z toho vyplývajúcich skrivodlivostí, intríg, bojov o lepšie postavenie, viac peňazí, korupcie, pokrytectva a pretvárky, šikany zo strany nadriadených, pätolizačstva podriadených... V takýchto ZMAR spoločenstvách nakoniec väčšinu ich členov spája iba ich nejaký egoizmus, hrabivosť, nenásytnosť po stále väčšej moci a vyššom postavení a strach, že o svoje postavenie a výhody prídu. Ich spoločná pretvárka a spoločné lži, ktoré ich kryjú a ktoré ich krivia.

Ako sa zorganizovať bez takéhoto zla, ktoré je samo o sebe zlom a zdrojom zla šíreným do celej spoločnosti? Nie tak ako oni, ale opačne, nie mocensky zhora dole, ale slobodne, od každého jedného človeka takto:

Desiati, alebo podobne primeraný počet najbližších Slovӕnov slobodného ducha v mieste kde sú, si vytvoria svoj kruh v ktorom sa môžu pravidelne stretať, vypočuť sa, na niečom sa dohodnúť. V tomto 1.kruhu sa pravidelne stretať a riešiť veci, ktoré môžu vyriešiť a pomáhať si ich uskutočniť a tak roztáčať a oživovať tento svoj vlastný kruh.

A zároveň si vo svojom kruhu (akokoľvek) zvoliť zástupcu tohto kruhu, ktorý bude tento 1.kruh zastupovať v 2.kruhu. Za zástupcu kruhu si môžu členovia kruhu zvoliť akokoľvek sa dohodnú a kohokoľvek z kruhu a to na ktoromkoľvek stretnutí kruhu. Nemusí a ani by nemal byť zástupca kruhu volený na nejaké volebné obdobie. Tak, ako môže byť na ktoromkoľvek stretnutí zvolený, rovnako môže byť aj na ktoromkoľvek stretnutí v prípade potreby vymenený. Je zvolený, vybraný, alebo vylosovaný tak, ako chcú členovia kruhu. Či už hlasovaním, losom, alebo sa môžu členovia kruhu v tejto funkcii striedať, ak chcú tak, že na každom stretnutí kruhu sa zástupcom kruhu stane ďalší v poradí podľa toho, ako v kruhu sedia, alebo podľa abecedy, alebo akokoľvek sa dohodnú. V každom kruhu si jeho členovia určujú svojho zástupcu tak, ako to považujú sa potrebné, podľa toho, ako a koho sami uznajú za najlepšieho a najvhodnejšieho v danom čase.

Prečo je potrebný zástupca každého kruhu? Aby sa títo zástupcovia 1.kruhov (kruhov 1. stupňa) mohli pravidelne stretať v 2.kruhu (kruhu 2. stupňa - kruhu zástupcov najbližších/susedných kruhov 1. stupňa). Aby prostredníctvom tohto 2.kruhu mohli susedné 1.kruhy medzi sebou spolupracovať na väčších projektoch, vo väčšom počte, na vyššom stupni.

Prostredníctvom 2.kruhu by už takto mohlo efektívne spolupracovať až stovka Slovӕnov slobodného ducha buď priamo, alebo prostredníctvom zástupcu ich kruhov. Pravidelne sa v kruhoch stretať a posúvať ďalej seba, svoj kruh a aj susedné kruhy.

V každom kruhu riešia jeho členovia veci, ktoré možno v kruhu vyriešiť. So svojimi návrhmi, ponukami, alebo potrebami poverujú svojho zástupcu, ktorý ich tlmočí zástupcom iných kruhov na stretnutiach 2.kruhu. Tam riešia títo zástupcovia 1.kruhov všetky veci im zverené, ktoré spolu rozoberajú a hľadajú najlepšie možnosti a riešenie na tomto 2.stupni. Hľadajú spoločné prieniky, v čom a ako si môžu navzájom pomôcť atď.

Na ďalšom stretnutí 1.kruhov vyslaní zástupcovia tlmočia členom 1.kruhov všetky veci, ktoré sa podarilo dohodnúť a ako. Tam s nimi oboznámia ostatných členov a spolu s nimi premyslia do čoho a ako sa zapoja. Aby sa mohli veci napevno dohodnúť, rozbehnúť a v spolupráci s ostatnými nakoniec aj podariť čo najlepšie a dokončiť. Buď pomôcť dobrej veci, alebo zastaviť vec zlú. Posúvať dobré veci a aj seba ďalej. Rozvíjať ich aj seba v kruhoch.

A tak ďalej analogicky aj na vyšších stupňoch. V 2.kruhu si tento kruh zvolí zástupcu tohto 2.kruhu spôsobom, aký uzná za najvhodnejšie. Zástupcovia najbližších kruhov 2.stupňa sa potom stretávajú v 3.kruhu (na treťom stupni). A takto môžu v kruhoch prvých, druhých a treťom spolupracovať stovky až do tisíc Slovӕnov. Pravidelne sa stretať v kruhoch, byť spolu v kontakte, riešiť veci, posúvať a rozvíjať veci a aj seba samých. Udržovať, oživovať a roztáčať ďalšie kruhy.

Všetko rastie najskôr z malého do väčšieho. Všetko rastie z dola nahor. Najskôr ľudia musia spolu vykresať/vytvoriť/roztožiť 1.kruh a riešiť v ňom spoločné veci. Postupne ho roztáčať a oživovať na pravidelných stretnutiach. Až keď bude viacero takýchto 1.kruhov točiacich sa svojou rýchlosťou, pravidelne sa stretajúcich, živých, môžu ich zástupcovia vytvoriť/roztožiť/vykresať aj kruh na vyššom stupni – 2.kruh. A až keď budú desiatky 1. kruhov a viacero 2.kruhov živých, stretajúcich sa, točiacich sa, môžu zástupcovia týchto 2.kruhov roztočiť aj 3.kruh, prostredníctvom ktorého už môže slobodne spolupracovať až do tisíc Slovӕnov slobodného ducha.

Možno sa to niekomu môže stále zdať málo, ale týmto spôsobom, s rastúcim počtom kruhov, by už možno vytvorením 5.kruhu, ale najneskôr vytvorením 7.kruhu (kruhu na 7.stupni) mohol byť v spojení so všetkými ostatnými a spolu slobodne spolupracovať každý Sloven (hanlivým čechizmom Slovák), ktorý by spolu s ostatnými spolupracovať chcel. A potom by nebolo žiadnej väčšej sily na Slovensku.

A najneskôr vytvorením 9. kruhu (kruhu na 9.stupni) by takto mohli slobodne spolupracovať všetci Slovania, ktorí by spolupracovať chceli. A potom by nebolo žiadnej väčšej sily v celom slovanskom svete.

A najneskôr vytvorením 10. kruhu (kruhu na 10.stupni) by takto mohli slobodne spolupracovať všetci ľudia, ktorí by spolupracovať chceli. A potom by nebolo žiadnej väčšej sily na svete - na Zemi.
